version: 2
jobs:
  # build cmd/tldr
  build:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/tombell/tldr
    steps:
      - checkout
      - run: |
          go get -u github.com/tombell/lodge/cmd/lodge
          make dev

  # build cmd/tldr with VERSION set to git tag
  build-release:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/tombell/tldr
    steps:
      - checkout
      - run: |
          go get -u github.com/tombell/lodge/cmd/lodge
          VERSION="${CIRCLE_TAG}" make dist
      - save_cache:
          key: dist-{{ .Revision }}
          paths:
            - dist/

  # run releasekit to generate release notes and attach build artifacts
  release:
    docker:
      - image: circleci/golang:1.10.1
    working_directory: /go/src/github.com/tombell/tldr
    steps:
      - checkout
      - restore_cache:
          keys:
            - dist-{{ .Revision }}
      - run: |
          go get -u github.com/tombell/releasekit/cmd/releasekit
          releasekit -t ${GITHUB_TOKEN} \
                     -o tombell \
                     -r tldr \
                     -p $(git tag | sort -V | tail -2 | head -1) \
                     -n ${CIRCLE_TAG} \
                     --attachment dist/tldr-linux-amd64 \
                     --attachment dist/tldr-darwin-amd64 \
                     --attachment dist/tldr-windows-amd64

workflows:
  version: 2
  build-n-release:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - release:
          requires:
            - build-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
